//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EneScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace EneScript {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class EneScriptLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, AND=14, OR=15, OWARI=16, WS=17, 
		ID=18, NUMBER=19, STRING=20, COMMENT=21, NEWLINE=22;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "AND", "OR", "OWARI", "WS", "ID", "NUMBER", 
		"STRING", "COMMENT", "NEWLINE", "KANJI", "KANA", "ZEN_ALNUM", "ASCII_ALNUM"
	};


	public EneScriptLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public EneScriptLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'\\uFF03\\uFF03'", "'\\uFF03\\uFF03\\uFF03'", "'\\u203B'", "'\\uFF08'", 
		"'\\uFF09'", "'\\u2192'", "'\\uFF1A'", "'\\uFF1D'", "'\\uFF01\\uFF1D'", 
		"'\\uFF1C'", "'\\uFF1C\\uFF1D'", "'\\uFF1E'", "'\\uFF1E\\uFF1D'", "'\\u304B\\u3064'", 
		"'\\u307E\\u305F\\u306F'", "'\\u7D42\\u308F\\u308A'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, "AND", "OR", "OWARI", "WS", "ID", "NUMBER", "STRING", "COMMENT", 
		"NEWLINE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "EneScript.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static EneScriptLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,22,163,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,
		6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,
		7,14,2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,
		7,21,2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,1,0,1,0,1,0,1,1,1,1,1,1,1,
		1,1,2,1,2,1,3,1,3,1,4,1,4,1,5,1,5,1,6,1,6,1,7,1,7,1,8,1,8,1,8,1,9,1,9,
		1,10,1,10,1,10,1,11,1,11,1,12,1,12,1,12,1,13,1,13,1,13,1,14,1,14,1,14,
		1,14,1,15,1,15,1,15,1,15,1,16,4,16,98,8,16,11,16,12,16,99,1,16,1,16,1,
		17,1,17,1,17,1,17,1,17,4,17,109,8,17,11,17,12,17,110,1,18,4,18,114,8,18,
		11,18,12,18,115,1,19,1,19,5,19,120,8,19,10,19,12,19,123,9,19,1,19,1,19,
		1,19,5,19,128,8,19,10,19,12,19,131,9,19,1,19,3,19,134,8,19,1,20,1,20,1,
		20,1,20,5,20,140,8,20,10,20,12,20,143,9,20,1,20,1,20,1,20,1,20,1,21,3,
		21,150,8,21,1,21,1,21,3,21,154,8,21,1,22,1,22,1,23,1,23,1,24,1,24,1,25,
		1,25,3,121,129,141,0,26,1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,8,17,9,19,10,
		21,11,23,12,25,13,27,14,29,15,31,16,33,17,35,18,37,19,39,20,41,21,43,22,
		45,0,47,0,49,0,51,0,1,0,7,3,0,9,9,32,32,12288,12288,1,0,65296,65305,2,
		0,10,10,13,13,1,0,19968,40869,1,0,12352,12543,3,0,65296,65305,65313,65338,
		65345,65370,3,0,48,57,65,90,97,122,171,0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,
		0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,0,17,
		1,0,0,0,0,19,1,0,0,0,0,21,1,0,0,0,0,23,1,0,0,0,0,25,1,0,0,0,0,27,1,0,0,
		0,0,29,1,0,0,0,0,31,1,0,0,0,0,33,1,0,0,0,0,35,1,0,0,0,0,37,1,0,0,0,0,39,
		1,0,0,0,0,41,1,0,0,0,0,43,1,0,0,0,1,53,1,0,0,0,3,56,1,0,0,0,5,60,1,0,0,
		0,7,62,1,0,0,0,9,64,1,0,0,0,11,66,1,0,0,0,13,68,1,0,0,0,15,70,1,0,0,0,
		17,72,1,0,0,0,19,75,1,0,0,0,21,77,1,0,0,0,23,80,1,0,0,0,25,82,1,0,0,0,
		27,85,1,0,0,0,29,88,1,0,0,0,31,92,1,0,0,0,33,97,1,0,0,0,35,108,1,0,0,0,
		37,113,1,0,0,0,39,133,1,0,0,0,41,135,1,0,0,0,43,153,1,0,0,0,45,155,1,0,
		0,0,47,157,1,0,0,0,49,159,1,0,0,0,51,161,1,0,0,0,53,54,5,65283,0,0,54,
		55,5,65283,0,0,55,2,1,0,0,0,56,57,5,65283,0,0,57,58,5,65283,0,0,58,59,
		5,65283,0,0,59,4,1,0,0,0,60,61,5,8251,0,0,61,6,1,0,0,0,62,63,5,65288,0,
		0,63,8,1,0,0,0,64,65,5,65289,0,0,65,10,1,0,0,0,66,67,5,8594,0,0,67,12,
		1,0,0,0,68,69,5,65306,0,0,69,14,1,0,0,0,70,71,5,65309,0,0,71,16,1,0,0,
		0,72,73,5,65281,0,0,73,74,5,65309,0,0,74,18,1,0,0,0,75,76,5,65308,0,0,
		76,20,1,0,0,0,77,78,5,65308,0,0,78,79,5,65309,0,0,79,22,1,0,0,0,80,81,
		5,65310,0,0,81,24,1,0,0,0,82,83,5,65310,0,0,83,84,5,65309,0,0,84,26,1,
		0,0,0,85,86,5,12363,0,0,86,87,5,12388,0,0,87,28,1,0,0,0,88,89,5,12414,
		0,0,89,90,5,12383,0,0,90,91,5,12399,0,0,91,30,1,0,0,0,92,93,5,32066,0,
		0,93,94,5,12431,0,0,94,95,5,12426,0,0,95,32,1,0,0,0,96,98,7,0,0,0,97,96,
		1,0,0,0,98,99,1,0,0,0,99,97,1,0,0,0,99,100,1,0,0,0,100,101,1,0,0,0,101,
		102,6,16,0,0,102,34,1,0,0,0,103,109,3,45,22,0,104,109,3,47,23,0,105,109,
		3,49,24,0,106,109,3,51,25,0,107,109,5,95,0,0,108,103,1,0,0,0,108,104,1,
		0,0,0,108,105,1,0,0,0,108,106,1,0,0,0,108,107,1,0,0,0,109,110,1,0,0,0,
		110,108,1,0,0,0,110,111,1,0,0,0,111,36,1,0,0,0,112,114,7,1,0,0,113,112,
		1,0,0,0,114,115,1,0,0,0,115,113,1,0,0,0,115,116,1,0,0,0,116,38,1,0,0,0,
		117,121,5,12300,0,0,118,120,8,2,0,0,119,118,1,0,0,0,120,123,1,0,0,0,121,
		122,1,0,0,0,121,119,1,0,0,0,122,124,1,0,0,0,123,121,1,0,0,0,124,134,5,
		12301,0,0,125,129,5,12302,0,0,126,128,8,2,0,0,127,126,1,0,0,0,128,131,
		1,0,0,0,129,130,1,0,0,0,129,127,1,0,0,0,130,132,1,0,0,0,131,129,1,0,0,
		0,132,134,5,12303,0,0,133,117,1,0,0,0,133,125,1,0,0,0,134,40,1,0,0,0,135,
		136,5,65284,0,0,136,137,5,65284,0,0,137,141,1,0,0,0,138,140,9,0,0,0,139,
		138,1,0,0,0,140,143,1,0,0,0,141,142,1,0,0,0,141,139,1,0,0,0,142,144,1,
		0,0,0,143,141,1,0,0,0,144,145,5,65284,0,0,145,146,1,0,0,0,146,147,6,20,
		0,0,147,42,1,0,0,0,148,150,5,13,0,0,149,148,1,0,0,0,149,150,1,0,0,0,150,
		151,1,0,0,0,151,154,5,10,0,0,152,154,5,13,0,0,153,149,1,0,0,0,153,152,
		1,0,0,0,154,44,1,0,0,0,155,156,7,3,0,0,156,46,1,0,0,0,157,158,7,4,0,0,
		158,48,1,0,0,0,159,160,7,5,0,0,160,50,1,0,0,0,161,162,7,6,0,0,162,52,1,
		0,0,0,11,0,99,108,110,115,121,129,133,141,149,153,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace EneScript
