//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EneScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace EneScript {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="EneScriptParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IEneScriptVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="EneScriptParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] EneScriptParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StatementLine</c>
	/// labeled alternative in <see cref="EneScriptParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatementLine([NotNull] EneScriptParser.StatementLineContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>EmptyLine</c>
	/// labeled alternative in <see cref="EneScriptParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEmptyLine([NotNull] EneScriptParser.EmptyLineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EneScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] EneScriptParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EneScriptParser.eventHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventHeader([NotNull] EneScriptParser.EventHeaderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EneScriptParser.triggerHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTriggerHeader([NotNull] EneScriptParser.TriggerHeaderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EneScriptParser.logic"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogic([NotNull] EneScriptParser.LogicContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EneScriptParser.target"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTarget([NotNull] EneScriptParser.TargetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EneScriptParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] EneScriptParser.CommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EneScriptParser.arg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArg([NotNull] EneScriptParser.ArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EneScriptParser.dialogue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDialogue([NotNull] EneScriptParser.DialogueContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AndExpr</c>
	/// labeled alternative in <see cref="EneScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpr([NotNull] EneScriptParser.AndExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ValueExpr</c>
	/// labeled alternative in <see cref="EneScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueExpr([NotNull] EneScriptParser.ValueExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FunctionExpr</c>
	/// labeled alternative in <see cref="EneScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionExpr([NotNull] EneScriptParser.FunctionExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>RelationalExpr</c>
	/// labeled alternative in <see cref="EneScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalExpr([NotNull] EneScriptParser.RelationalExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="EneScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenExpr([NotNull] EneScriptParser.ParenExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>OrExpr</c>
	/// labeled alternative in <see cref="EneScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpr([NotNull] EneScriptParser.OrExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EneScriptParser.relationOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationOp([NotNull] EneScriptParser.RelationOpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EneScriptParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCall([NotNull] EneScriptParser.FuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EneScriptParser.funcArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncArg([NotNull] EneScriptParser.FuncArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="EneScriptParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] EneScriptParser.ValueContext context);
}
} // namespace EneScript
